### ISSUE TITLE
Suggestion: Add condition 114 on last X players alive

### ISSUE THREAD

**Issue by Starblaster64** [Chdata/Versus-Saxton-Hale#19]
So the new "Upon spawning, friendly players will show an outline for 10 seconds" feature is actually contained in condition 114. A player with condition 114 will see all other friendly players with the Spectator x-ray feature.
Would adding this condition to all non-Hale players when there are only a handful or less players alive be a good idea?

**Comment by Chdata** [comment]
I don't think it matters if you can see your team with that. There's a few niche scenarios where it might help you locate someone when nobody will ghost him, but we're better off looking in to setting outline on the final 2 via the netprop so Hale can see too, if we want that as an option for anti-stall.

**Comment by Starblaster64** [comment]
I was imagining a scenario where the last ~5 players alive could locate each other on larger maps, then the last 1-2 players would have the outline on themselves and Hale.
Regardless, having just one rather than both is probably all right. Closing.
