### ISSUE TITLE
Hale gibs material download.

### ISSUE THREAD

**Issue by jackemerson** [Chdata/Versus-Saxton-Hale#2]
The line (191) for adding the download is  "materials/models/player/saxton_test4/haleGibs.vmt",
The file isn't capitalised though and I believe this causes an issue.

**Comment by Starblaster64** [comment]
From what I've read on the AlliedModders forums, capitilising file names causes compatibility issues with Linux servers so the file is correct, and line(191) is in the wrong.

Also I believe Chdata should have removed the Hale gibs until further notice, as noted in commit 59d79e8, I suppose he simply ignored/forgot the material files.

**Comment by Chdata** [comment]
I left that material file in, as I wasn't sure if any of the other materials used it or not - like how the old Hale materials are actually used for CBS as well and are still included.

And yes, I wish it were all lowercase, but thePFA still capped it for some reason.

**Comment by Chdata** [comment]
Either way the gibs aren't in (models) and if it's only the gib material that's broken it's not a pressing issue as it's unused anyway.

**Comment by jackemerson** [comment]
Ah, yeah, I just updated the line in my code when I noticed it to stop the download request each map. 

@Starblaster64 In regards to capitalising causing issues, is that only if the code doesn't match case exactly or would you want to avoid having actual files capitalised on Linux?

**Comment by Starblaster64** [comment]
@Advkt Chdata is probably better qualified to answer that, but I would probably guess the latter.

**Comment by Chdata** [comment]
While it may be unnecessary, I believe it's best for all files to be all lowercase, _underscore instead of space, and [a-zA-Z1-0], or however that goes. At the very least, you won't ever run into problems doing that.

But yeah if it is trying to download something that's not there I guess I'll comment it out.

**Comment by Chdata** [comment]
Closed by https://github.com/Chdata/Versus-Saxton-Hale/commit/013f849a3a7cd9c59b6616699e87c4a79e3acf84
