### ISSUE TITLE
Rocket Launchers have an extra un-mentioned attribute

### ISSUE THREAD

**Issue by Starblaster64** [Chdata/Versus-Saxton-Hale#3]
I've already told you about this Chdata, but I wanted to make an issue anyway.

All Soldier rocket launchers (minus the CM5K and the Direct Hit) are currently given 1 point of the Rocket Specialist upgrade from MvM, which was not a noted change anywhere. In addition, rockets launched from rocket launchers with this attribute will still stun the Vagineer even while he's in his rage Uber for a short duration.

So I guess you can either remove the attribute, or add the change into the changelog.

**Comment by Chdata** [comment]
was gonna remove

**Comment by Chdata** [comment]
Closed by https://github.com/Chdata/Versus-Saxton-Hale/commit/fe8a0aa3fd7cdf658469748c55e14c58835c80c5
