### ISSUE TITLE
Sniper wallclimb with Tribalman's Shiv causes bleed

### ISSUE THREAD

**Issue by Starblaster64** [Chdata/Versus-Saxton-Hale#5]
Completely expected behaviour with the way wall-climbing is set up. I simply thought it would be worth noting in-case you wanted to remove it. Personally I find it fine as is, since you can actually achieve some higher jumps due to the bleed damage, at the cost of, well, bleeding.

**Comment by Chdata** [comment]
Woops, that's fixed in my version but I guess I didn't copy it correctly.

**Comment by Chdata** [comment]
Closed by https://github.com/Chdata/Versus-Saxton-Hale/commit/04351436aaab6ae74d8cec98bfe921dee43fcc6a
